# https://taskfile.dev

version: '3'

tasks:
  setup:agents:
    desc: prepare repo for claude agent
    silent: true
    cmds:
      - rm -f .claude/CLAUDE.md
      - rm -f AGENTS.md
      - mkdir -p .agents .claude
      - cmd: |
          pwsh -Command "New-Item -ItemType SymbolicLink -Path .claude/CLAUDE.md -Target ../.agents/AGENTS.md -Force | Out-Null"
          pwsh -Command "New-Item -ItemType SymbolicLink -Path AGENTS.md -Target .agents/AGENTS.md -Force | Out-Null"
        platforms: [windows]
      - cmd: |
          ln -sfn ../.agents/AGENTS.md .claude/CLAUDE.md
          ln -sfn ../.agents/AGENTS.md AGENTS.md
        platforms: [linux, darwin]
      - echo "✅ Linked .agents/AGENTS.md to .claude/CLAUDE.md and AGENTS.md"
      - cmd: |
          # check if .gitignore has .claude or AGENTS.md, if not add them
          if ! grep -q "^.claude$" .gitignore; then
            echo -e "\n.claude" >> .gitignore
            echo "✅ Added .claude to .gitignore"
          else
            echo "✅ .claude is already in .gitignore"
          fi
          if ! grep -q "^/AGENTS.md$" .gitignore; then
            echo -e "\n/AGENTS.md" >> .gitignore
            echo "✅ Added AGENTS.md to .gitignore"
          else
            echo "✅ AGENTS.md is already in .gitignore"
          fi
          
  dev:
    cmds:
      - cargo +stable watch -x "run server --force"

  dev:nowatch:
    cmds:
      - cargo +stable run server --force

  build:release:
    desc: ⚡ build kurv «release»
    cmds:
      - cargo +stable build --release
      - python check_size.py

  fmt:check:
    cmds:
      - cargo +nightly fmt --all --check

  lint:check:
    cmds:
      - cargo +stable clippy --workspace --all-targets --all-features

  lint:
    cmds:
      - cargo +stable clippy --workspace --all-targets --all-features --fix --allow-staged

  check:
    cmds:
      - task: fmt:check
      - task: lint:check

  fmt:
    cmds:
      - cargo +nightly fmt --all

  build:
    desc: ⚡ build kurv «debug»
    cmds:
      - cargo +stable build
      - python check_size.py

  # the following tasks are for testing the ci workflow locally, using the
  # nektosact.com tool

  local-ci-release:
    desc: 🚀 run local ci workflow «release»
    cmds:
      - |
        act push \
          -W="./.github/workflows/ci.yml" \
          -e="./.github/act-test/release.json" \
          --secret-file="./.github/act-test/secrets.env" \
          --pull=false

  local-ci-pub:
    desc: 🚀 run local ci workflow «publish»
    cmds:
      - |
        act release \
          -W="./.github/workflows/publish.yml" \
          -e="./.github/act-test/publish.json" \
          --secret-file="./.github/act-test/secrets.env" \
          --pull=false \
          --reuse