name: "✅ » checks"

on:
  workflow_call:

defaults:
  run:
    shell: 'bash'

jobs:
  check:
    name: "✅ » check"
    runs-on: ubuntu-latest
    steps:
      - name: 📁 » checkout repository
        uses: actions/checkout@v6

      - name: 🦀 » install stable rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - name: 🦀 » install nightly rust (for rustfmt)
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: 🗃️ » cache cargo
        uses: Swatinem/rust-cache@v2
     
      - name: 🧊 » install Task
        uses: go-task/setup-task@v2
        with:
          version: 3.x

      - name: 🏗️ » build kurv
        run: task build

      - name: 🧪 » test kurv
        run: cargo test
      
      - name: 🕵️ » check lint & format
        run: task check
